# use query string ?reload-config to force reloading this file, otherwise cahced in session
# live section is used for live (www.) and test (test.)
# dev section is used for dev (dev.)

site_id: 247

settings:
  config_file: config/config.json

system_cache: off
redis_cache: off
mongo_cache: on

some:
  other:
    value: foobar
    